### ISSUE TITLE
[TODO] Implement tests

### ISSUE THREAD

**Issue by jhmaster2000** [jhmaster2000/utc-date#1]
*I keep procrastinating on this so I'm leaving this here to force myself into it.*

Implement all the testing non-sense with /tests/*.test.js and code coverage and etc.

Checklist:

- [x] Setup /tests/
- [x] Make *.test.js files
- [x] Setup testing library (devDependency)
- [x] Setup code coverage (^?)
- [x] Probably something else I'm forgetting right now (I did forget quite a few things)

**Comment by jhmaster2000** [comment]
Coverage works locally, gotta setup coveralls but I will do that later, actual tests work (mostly) so i'm done with this for now.
